# API 1 Scenario 1
GET http://localhost:3000/todos/?status=TO%20DO

###

# API 1 Scenario 2
GET http://localhost:3000/todos/?priority=HIGH

###

# API 1 Scenario 3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%PROGRESS

###

# API 1 Scenario 4
GET http://localhost:3000/todos/?search_q=Eating

###

# API 2
GET http://localhost:3000/todos/1

###

# API 3
POST http://localhost:3000/todos
Content-Type: application/json

{
  "id": 8,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}


###

# API 4
PUT  http://localhost:3000/todos/1
Content-Type: application/json

{
    "status": "DONE"
}

###

PUT  http://localhost:3000/todos/1
Content-Type: application/json

{
    "priority": "HIGH"
}

###

# API 5
DELETE  http://localhost:3000/todos/6

